<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE Applications [
   <!ELEMENT Applications (Application)*>
   <!ATTLIST Applications
      xmlns CDATA #REQUIRED>
   <!ELEMENT Application (Customer|Accounts|Users|Agreements)*>
   <!ELEMENT Customer (AccountHolder)*>
   <!ATTLIST Customer
      type CDATA #REQUIRED
      prefix CDATA #REQUIRED
      md_status_nonpro CDATA #REQUIRED
      external_id CDATA #REQUIRED
      email CDATA #REQUIRED>
   <!ELEMENT AccountHolder (AccountHolderDetails|FinancialInformation|RegulatoryInformation|TaxInformation)*>
   <!ELEMENT AccountHolderDetails (Name|DOB|MaritalStatus|NumDependents|Residence|MailingAddress|Phones|Email|Identification|EmploymentType|EmploymentDetails|Ownership|Title)*>
   <!ATTLIST AccountHolderDetails
      same_mail_address CDATA #REQUIRED
      external_id CDATA #REQUIRED>
   <!ELEMENT Name (#PCDATA)>
   <!ATTLIST Name
      middle CDATA #REQUIRED
      last CDATA #REQUIRED
      first CDATA #REQUIRED>
   <!ELEMENT DOB (#PCDATA)>
   <!ELEMENT MaritalStatus (#PCDATA)>
   <!ELEMENT NumDependents (#PCDATA)>
   <!ELEMENT Residence (#PCDATA)>
   <!ATTLIST Residence
      street_2 CDATA #REQUIRED
      street_1 CDATA #REQUIRED
      state CDATA #REQUIRED
      postal_code CDATA #REQUIRED
      country CDATA #REQUIRED
      city CDATA #REQUIRED>
   <!ELEMENT MailingAddress (#PCDATA)>
   <!ATTLIST MailingAddress
      street_1 CDATA #REQUIRED
      state CDATA #REQUIRED
      postal_code CDATA #REQUIRED
      country CDATA #REQUIRED
      city CDATA #REQUIRED>
   <!ELEMENT Phones (#PCDATA)>
   <!ATTLIST Phones
      secondary CDATA #REQUIRED
      primary CDATA #REQUIRED>
   <!ELEMENT Email (#PCDATA)>
   <!ATTLIST Email
      email CDATA #REQUIRED>
   <!ELEMENT Identification (#PCDATA)>
   <!ATTLIST Identification
      citizenship CDATA #REQUIRED
      SSN CDATA #REQUIRED
      LegalResidenceState CDATA #REQUIRED
      LegalResidenceCountry CDATA #REQUIRED>
   <!ELEMENT EmploymentType (#PCDATA)>
   <!ELEMENT EmploymentDetails (employer|occupation|employer_business|employer_address|employer_phone)*>
   <!ELEMENT employer (#PCDATA)>
   <!ELEMENT occupation (#PCDATA)>
   <!ELEMENT employer_business (#PCDATA)>
   <!ELEMENT employer_address (#PCDATA)>
   <!ATTLIST employer_address
      street_2 CDATA #REQUIRED
      street_1 CDATA #REQUIRED
      state CDATA #REQUIRED
      postal_code CDATA #REQUIRED
      country CDATA #REQUIRED
      city CDATA #REQUIRED>
   <!ELEMENT employer_phone (#PCDATA)>
   <!ELEMENT Ownership (#PCDATA)>
   <!ATTLIST Ownership
      percentage CDATA #REQUIRED>
   <!ELEMENT Title (#PCDATA)>
   <!ATTLIST Title
      code CDATA #REQUIRED>
   <!ELEMENT FinancialInformation (InvestmentExperience)*>
   <!ATTLIST FinancialInformation
      net_worth CDATA #REQUIRED
      liquid_net_worth CDATA #REQUIRED
      annual_net_income CDATA #REQUIRED
      total_assets CDATA #REQUIRED>
   <!ELEMENT InvestmentExperience (AssetExperience)*>
   <!ELEMENT AssetExperience (#PCDATA)>
   <!ATTLIST AssetExperience
      asset_class CDATA #REQUIRED
      knowledge_level CDATA #REQUIRED
      trades_per_year CDATA #REQUIRED
      years_trading CDATA #REQUIRED>
   <!ELEMENT RegulatoryInformation (RegulatoryDetail|AffiliationDetails)*>
   <!ELEMENT RegulatoryDetail (#PCDATA)>
   <!ATTLIST RegulatoryDetail
      code CDATA #REQUIRED
      detail CDATA #IMPLIED
      status CDATA #REQUIRED>
   <!ELEMENT AffiliationDetails (affiliation_relationship|person_name|company|company_mailing_address|company_phone)*>
   <!ELEMENT affiliation_relationship (#PCDATA)>
   <!ELEMENT person_name (#PCDATA)>
   <!ELEMENT company (#PCDATA)>
   <!ELEMENT company_mailing_address (#PCDATA)>
   <!ATTLIST company_mailing_address
      street_1 CDATA #REQUIRED
      state CDATA #REQUIRED
      postal_code CDATA #REQUIRED
      country CDATA #REQUIRED
      city CDATA #REQUIRED>
   <!ELEMENT company_phone (#PCDATA)>
   <!ELEMENT TaxInformation (W9)*>
   <!ELEMENT W9 (#PCDATA)>
   <!ATTLIST W9
      tin_type CDATA #REQUIRED
      tin CDATA #REQUIRED
      name CDATA #REQUIRED
      customer_type CDATA #REQUIRED
      cert3 CDATA #REQUIRED
      cert2 CDATA #REQUIRED
      cert1 CDATA #REQUIRED>
   <!ELEMENT Accounts (Account)*>
   <!ELEMENT Account (InvestmentObjectives|TradingPermissions|AdvisorWrapFees|DepositNotification)*>
   <!ATTLIST Account
      multicurrency CDATA #REQUIRED
      margin CDATA #REQUIRED
      external_id CDATA #REQUIRED
      base_currency CDATA #REQUIRED>
   <!ELEMENT InvestmentObjectives (objective)*>
   <!ELEMENT objective (#PCDATA)>
   <!ELEMENT TradingPermissions (TradingPermission)*>
   <!ELEMENT TradingPermission (#PCDATA)>
   <!ATTLIST TradingPermission
      exchange_group CDATA #REQUIRED>
   <!ELEMENT AdvisorWrapFees (automated_fees_details)*>
   <!ATTLIST AdvisorWrapFees
      strategy CDATA #REQUIRED>
   <!ELEMENT automated_fees_details (#PCDATA)>
   <!ATTLIST automated_fees_details
      type CDATA #REQUIRED
      max_fee CDATA #REQUIRED>
   <!ELEMENT DepositNotification (CheckDetails)*>
   <!ATTLIST DepositNotification
      type CDATA #REQUIRED
      currency CDATA #REQUIRED
      amount CDATA #REQUIRED>
   <!ELEMENT CheckDetails (#PCDATA)>
   <!ATTLIST CheckDetails
      routing_number CDATA #REQUIRED
      acct_number CDATA #REQUIRED>
   <!ELEMENT Users (User)*>
   <!ELEMENT User (#PCDATA)>
   <!ATTLIST User
      prefix CDATA #REQUIRED
      external_user_id CDATA #REQUIRED
      external_individual_id CDATA #REQUIRED>
   <!ELEMENT Agreements (Agreement)*>
   <!ELEMENT Agreement (#PCDATA)>
   <!ATTLIST Agreement
      exec_login_ts CDATA #REQUIRED
      exec_ts CDATA #REQUIRED
      form_no CDATA #REQUIRED
      signature CDATA #IMPLIED>
   ]>
<Applications xmlns="http://www.interactivebrokers.com/schemas/IBCust_import">
    <Application>
        <Customer type="INDIVIDUAL" prefix="ecaim" md_status_nonpro="true" external_id="TC10492" email="hpadmana@mail">
            <AccountHolder>
                <AccountHolderDetails same_mail_address="true" external_id="TCI10492">
                    <Name middle="E" last="Munez" first="Frank"/>
                    <DOB>1968-04-01</DOB>
                    <MaritalStatus>M</MaritalStatus>
                    <NumDependents>2</NumDependents>
                    <Residence street_2="Apt. 11" street_1="111 Paradise Lane" state="NY" postal_code="11111" country="United States" city="Springfield"/>
                    <MailingAddress street_1="PO Box 111" state="NY" postal_code="12121" country="United States" city="Riverdale"/>
                    <Phones secondary="222-222-2222" primary="111-111-1111"/>
                    <Email email="hpadmana@mail"/>
                    <Identification citizenship="United States" SSN="111211111" LegalResidenceState="NY" LegalResidenceCountry="United States"/>
                    <EmploymentType>EMPLOYED</EmploymentType>
                    <EmploymentDetails>
                        <employer>Acme Inc.</employer>
                        <occupation>Chief Giggle Engineer</occupation>
                        <employer_business>Laugh Manufacturing</employer_business>
                        <employer_address street_2="Humor Way" street_1="1 Laugh Plaza" state="NY" postal_code="12123" country="United States" city="Riverdale"/>
                        <employer_phone>222-333-4444</employer_phone>
                    </EmploymentDetails>
                    <Ownership percentage="100"/>
                    <Title code="Account Holder"/>
                </AccountHolderDetails>
                <FinancialInformation net_worth="4" liquid_net_worth="4" annual_net_income="4" total_assets="4">
                    <InvestmentExperience>
                        <AssetExperience years_trading="6" trades_per_year="5" knowledge_level="Good" asset_class="STK"/>
                        <AssetExperience years_trading="6" trades_per_year="5" knowledge_level="Good" asset_class="OPT"/>
                        <AssetExperience years_trading="6" trades_per_year="5" knowledge_level="Good" asset_class="FUT"/>
                        <AssetExperience years_trading="1" trades_per_year="1" knowledge_level="Limited" asset_class="BOND"/>
                        <AssetExperience years_trading="0" trades_per_year="0" knowledge_level="Limited" asset_class="CASH"/>
                    </InvestmentExperience>
                </FinancialInformation>
                <RegulatoryInformation>
                    <RegulatoryDetail status="true" detail="Settlement beneficiary of a class action lawsuit against Grinch Corp." code="DISPUTE"/>
                    <RegulatoryDetail status="false" code="INVESTIGATION"/>
                    <RegulatoryDetail status="false" code="CRIMINAL"/>
                    <RegulatoryDetail status="false" code="MEMBERSHIP"/>
                    <RegulatoryDetail status="false" code="REGULATORYCONTROL"/>
                    <RegulatoryDetail status="false" code="CFTCREGISTERED"/>
                    <RegulatoryDetail status="false" code="IBACCOUNTS"/>
                    <RegulatoryDetail status="false" code="BROKERDEALER"/>
                    <RegulatoryDetail status="false" code="STOCKCONTROL"/>
                    <RegulatoryDetail status="true" code="AFFILIATION"/>
                    <RegulatoryDetail status="false" code="EXCHANGEMEMBERSHIP"/>
                    <AffiliationDetails>
                        <affiliation_relationship>Wife is Employee</affiliation_relationship>
                        <person_name>Jane Nueman</person_name>
                        <company>Interactive Brokers LLC</company>
                        <company_mailing_address street_1="1 Pickwick Plaza" state="CT" postal_code="06830" country="United States" city="Greenwich"/>
                        <company_phone>203-618-5700</company_phone>
                    </AffiliationDetails>
                </RegulatoryInformation>
                <TaxInformation>
                    <W9 tin_type="SSN" tin="111211111" name="Frank E Munez" customer_type="Individual" cert3="true" cert2="true" cert1="true"/>
                </TaxInformation>
            </AccountHolder>
        </Customer>
        <Accounts>
            <Account multicurrency="false" margin="RegT" external_id="TCA10492" base_currency="USD">
                <InvestmentObjectives>
                    <objective>Growth</objective>
                    <objective>Trading</objective>
                    <objective>Speculation</objective>
                </InvestmentObjectives>
                <TradingPermissions>
                    <TradingPermission exchange_group="US-Sec"/>
                </TradingPermissions>
                <AdvisorWrapFees strategy="AUTOMATED">
                    <automated_fees_details type="INVOICE_LIMIT_Q" max_fee="15"/>
                </AdvisorWrapFees>
                <DepositNotification type="CHECK" currency="USD" amount="5000.00">
                    <CheckDetails routing_number="123456789" acct_number="1234567890"/>
                </DepositNotification>
            </Account>
        </Accounts>
        <Users>
            <User prefix="ecaim" external_user_id="TCU10492" external_individual_id="TCI10492"/>
        </Users>
        <Agreements>
            <Agreement signature="Frank E Munez" form_no="3021" exec_ts="20091106125125" exec_login_ts="20091106125025"/>
            <Agreement signature="Frank E Munez" form_no="8250" exec_ts="20091106125225" exec_login_ts="20091106125025"/>
            <Agreement signature="Frank E Munez" form_no="3007" exec_ts="20091106125325" exec_login_ts="20091106125025"/>
            <Agreement signature="Frank E Munez" form_no="3012" exec_ts="20091106125330" exec_login_ts="20091106125025"/>
            <Agreement signature="Frank E Munez" form_no="2108" exec_ts="20091106125400" exec_login_ts="20091106125025"/>
            <Agreement signature="Frank E Munez" form_no="1005" exec_ts="20091106125401" exec_login_ts="20091106125025"/>
            <Agreement form_no="2109" exec_ts="20091106125502" exec_login_ts="20091106125025"/>
        </Agreements>
    </Application>
</Applications>

